### ISSUE TITLE
Generate user identifiers from Persistent Name IDs

### ISSUE THREAD

**Issue by z38** [its-dirg/SATOSA#49] opened 2016-10-18 14:43 UTC
I'm having trouble getting started with the SAML backend. Whenever I try to login an exception gets thrown:

```txt
[2016-10-18 15:00:37] [DEBUG]: [urn:uuid:e9b38285-e2a5-43e5-b11a-8aee973a597c] received attributes:
{
    "displayName": [
        "John Doe"
    ],
    "eduPersonScopedAffiliation": [
        "member"
    ],
    "eduPersonTargetedID": [
        {
            "NameID": {
                "name_qualifier": "https://idp.local/idp/sso",
                "format": "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent",
                "sp_name_qualifier": "https://satosa.local/example/proxy_saml2_backend.xml",
                "value": "KHj2iBGk+sAhaQw+lIVaxCdfJFw="
            }
        }
    ],
    "mail": [
        "john@example.com"
    ]
}
[2016-10-18 15:00:37] [ERROR]: [urn:uuid:e9b38285-e2a5-43e5-b11a-8aee973a597c] Uncaught exception
Traceback (most recent call last):
  File "/opt/satosa/src/satosa/base.py", line 256, in run
    resp = self._run_bound_endpoint(context, spec)
  File "/opt/satosa/src/satosa/base.py", line 204, in _run_bound_endpoint
    return spec(context)
  File "/opt/satosa/src/satosa/backends/saml2.py", line 162, in authn_response
    return self.auth_callback_func(context, self._translate_response(authn_response, context.state))
  File "/opt/satosa/src/satosa/base.py", line 165, in _auth_resp_callback_func
    self.config["INTERNAL_ATTRIBUTES"]["user_id_from_attrs"]]
  File "/opt/satosa/src/satosa/base.py", line 164, in <listcomp>
    user_id = ["".join(internal_response.attributes[attr]) for attr in
TypeError: sequence item 0: expected str instance, dict found
[2016-10-18 15:00:37] [ERROR]: Unknown error
Traceback (most recent call last):
  File "/opt/satosa/src/satosa/base.py", line 256, in run
    resp = self._run_bound_endpoint(context, spec)
  File "/opt/satosa/src/satosa/base.py", line 204, in _run_bound_endpoint
    return spec(context)
  File "/opt/satosa/src/satosa/backends/saml2.py", line 162, in authn_response
    return self.auth_callback_func(context, self._translate_response(authn_response, context.state))
  File "/opt/satosa/src/satosa/base.py", line 165, in _auth_resp_callback_func
    self.config["INTERNAL_ATTRIBUTES"]["user_id_from_attrs"]]
  File "/opt/satosa/src/satosa/base.py", line 164, in <listcomp>
    user_id = ["".join(internal_response.attributes[attr]) for attr in
TypeError: sequence item 0: expected str instance, dict found
```

#### internal_attributes.yml
```yml
attributes:
  displayname:
    openid: [nickname]
    saml: [displayName]
  edupersontargetedid:
    facebook: [id]
    openid: [sub]
    saml: [eduPersonTargetedID]
  mail:
    facebook: [email]
    openid: [email]
    saml: [email, emailAdress, mail]
hash: [edupersontargetedid]
user_id_from_attrs: [edupersontargetedid]
user_id_to_attr: edupersontargetedid
```

Is there a way I can still use `eduPersonTargetedID`?

**Comment by rebeckag** [comment] 2016-10-19 05:53
This should be fixed as of [v3.3.0](https://github.com/its-dirg/SATOSA/releases/tag/v3.3.0) which includes an updated pysaml2 dependency.

Is this still present in version later than that?

**Comment by z38** [comment] 2016-10-19 09:07
You're right, thank you! I'm sorry for not updating all dependencies.

Now `eduPersonTargetedID` is flattened and an access token is issued. However, the UserInfo endpoint throws an exception: 
```txt
[2016-10-19 10:56:35] [DEBUG]: [urn:uuid:f4f30b77-68f2-40bc-9788-4d4cba272563] Found registered endpoint: module name:'OIDC', endpoint: OIDC/userinfo
[2016-10-19 10:56:35] [ERROR]: [urn:uuid:f4f30b77-68f2-40bc-9788-4d4cba272563] Uncaught exception
Traceback (most recent call last):
  File "/opt/satosa/src/satosa/base.py", line 255, in run
    resp = self._run_bound_endpoint(context, spec)
  File "/opt/satosa/src/satosa/base.py", line 203, in _run_bound_endpoint
    return spec(context)
  File "/opt/satosa/src/satosa/frontends/openid_connect.py", line 337, in userinfo_endpoint
    response = self.provider.handle_userinfo_request(urlencode(context.request), headers)
  File "/opt/satosa/venv/lib/python3.4/site-packages/pyop/provider.py", line 428, in handle_userinfo_request
    response = OpenIDSchema(sub=introspection['sub'], **user_claims)
TypeError: type object got multiple values for keyword argument 'sub'
[2016-10-19 10:56:36] [ERROR]: Unknown error
Traceback (most recent call last):
  File "/opt/satosa/src/satosa/base.py", line 255, in run
    resp = self._run_bound_endpoint(context, spec)
  File "/opt/satosa/src/satosa/base.py", line 203, in _run_bound_endpoint
    return spec(context)
  File "/opt/satosa/src/satosa/frontends/openid_connect.py", line 337, in userinfo_endpoint
    response = self.provider.handle_userinfo_request(urlencode(context.request), headers)
  File "/opt/satosa/venv/lib/python3.4/site-packages/pyop/provider.py", line 428, in handle_userinfo_request
    response = OpenIDSchema(sub=introspection['sub'], **user_claims)
TypeError: type object got multiple values for keyword argument 'sub'
```

I already reported the issue to [pyop#6](https://github.com/its-dirg/pyop/issues/6) when we didn't use `eduPersonTargetedID`. However, it seems to be related to SATOSA.

**Comment by rebeckag** [comment] 2016-10-19 09:42
Yes, I recognize this issue as the same you reported earlier.
I still need more info (all configuration for SATOSA), since I haven't been able to reproduce it locally yet.

**Comment by z38** [comment] 2016-10-19 12:24
#### proxy_conf.yml

```yml
BASE: https://satosa.local
INTERNAL_ATTRIBUTES: "internal_attributes.yaml"
COOKIE_STATE_NAME: "SATOSA_STATE"
STATE_ENCRYPTION_KEY: "123123"
CUSTOM_PLUGIN_MODULE_PATHS:
  - "plugins/backends"
  - "plugins/frontends"
  - "plugins/micro_services"
BACKEND_MODULES:
  - "plugins/saml2_backend.yaml"
FRONTEND_MODULES:
  - "plugins/openid_connect_frontend.yaml"
MICRO_SERVICES: []
USER_ID_HASH_SALT: "123123"
LOGGING:
  version: 1
  formatters:
    simple:
      format: "[%(asctime)-19.19s] [%(levelname)-5.5s]: %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
    info_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: simple
      filename: info.log
      maxBytes: 10485760 # 10MB
      backupCount: 20
      encoding: utf8
  loggers:
    satosa:
      level: DEBUG
      handlers: [console]
      propagate: no
  root:
    level: INFO
    handlers: [info_file_handler]
```

#### internal_attributes.yaml

see above

#### plugins/saml2_backend.yaml

identical to `examples/plugins/backend/saml2_backend.yaml.example`

#### plugins/openid_connect_frontend.yaml

```yml
module: satosa.frontends.openid_connect.OpenIDConnectFrontend
name: oidc
config:
  signing_key_path: oidcsign.pem
  db_uri: mongodb://localhost/satosa
  provider:
    client_registration_supported: No
    response_types_supported: ["code"]
    subject_types_supported: ["pairwise"]
    scopes_supported: ["openid", "email", "profile"]
```

Please let me know in case you need more information to reproduce the issue.

**Closed** 2016-10-20 10:11 UTC

**Comment by rebeckag** [comment] 2016-10-20 10:22
v3.3.2 contains an updated pyop dependency which fixes the issue with the 'sub' claim.

Let me know if you still have issues after that upgrade.

**Comment by z38** [comment] 2016-10-20 21:38
Thank you for the fast fix! Now the `sub` claim gets properly propagated to the clients.

**Comment by rebeckag** [comment] 2016-10-21 04:58
Sure thing, thanks for reporting and testing it out! :)
